### ISSUE TITLE
Think of a better way to close the browsers, se we don't have to wait for the message delay

### ISSUE THREAD

**Issue by raristotelov** [DimitarGrozev/SeleniumDiscordBot#25]

**Comment by DimitarGrozev** [comment]
![image](https://user-images.githubusercontent.com/31180602/151441192-fc701102-0144-4a3b-a701-5c2231f3b9b5.png)

**Comment by DimitarGrozev** [comment]
https://stackoverflow.com/questions/50576597/periodically-checking-for-5-seconds-using-stopwatch-in-c-sharp
